In [1]:
import pickle

In [5]:
file = "expert_data/Hopper-v2.pkl"

In [6]:
objects = []
with (open(file, "rb")) as openfile:
    while True:
        try:
            objects.append(pickle.load(openfile))
        except EOFError:
            break

In [7]:
objects

[{'observations': array([[ 1.25229861e+00, -3.18844902e-03,  3.52164833e-03, ...,
           8.49640448e-04, -4.95543739e-03, -3.89241199e-03],
         [ 1.25187361e+00, -3.25192457e-03,  3.31234071e-03, ...,
          -4.62423287e-02, -1.71163858e-02,  1.44455960e+00],
         [ 1.25058115e+00, -3.19879368e-03,  2.87119787e-03, ...,
          -6.06687417e-02, -2.07607846e-02,  2.88133999e+00],
         ...,
         [ 1.57104038e+00, -2.70470611e-02, -7.64099305e-02, ...,
          -1.02577234e+00,  3.00935329e+00,  6.62987310e+00],
         [ 1.57979881e+00, -2.36314303e-02, -8.25748254e-02, ...,
          -5.16503466e-01,  2.37480571e+00,  5.97890744e+00],
         [ 1.58769349e+00, -1.95297167e-02, -8.46352196e-02, ...,
           4.27895406e-04,  1.69780628e+00,  5.52297073e+00]]),
  'actions': array([[[ 0.02608132,  2.138234  ,  1.8916897 ]],
  
         [[ 0.06066349,  1.9349298 ,  1.7981125 ]],
  
         [[ 0.08049232,  1.6863072 ,  1.7177788 ]],
  
         ...,
  
       

In [15]:
observations = objects[0]['observations']
actions = objects[0]['actions']

In [17]:
observations.shape


(20000, 11)

In [18]:
actions.shape

(20000, 1, 3)

In [19]:
observations[0]

array([ 1.25229861e+00, -3.18844902e-03,  3.52164833e-03,  4.36515713e-03,
       -3.91071298e-03,  1.06249912e-04,  1.07338108e-03, -3.72655315e-03,
        8.49640448e-04, -4.95543739e-03, -3.89241199e-03])

In [20]:
type(observations)

numpy.ndarray

In [21]:
actions[0]

array([[0.02608132, 2.138234  , 1.8916897 ]], dtype=float32)

In [22]:
actions[1]

array([[0.06066349, 1.9349298 , 1.7981125 ]], dtype=float32)