In [33]:
import pickle
import numpy as np
import keras
import statistics as stats

In [2]:
file = "expert_data/Hopper-v2.pkl"

In [3]:
objects = []
with (open(file, "rb")) as openfile:
    while True:
        try:
            objects.append(pickle.load(openfile))
        except EOFError:
            break

In [4]:
objects

[{'observations': array([[ 1.25229861e+00, -3.18844902e-03,  3.52164833e-03, ...,
           8.49640448e-04, -4.95543739e-03, -3.89241199e-03],
         [ 1.25187361e+00, -3.25192457e-03,  3.31234071e-03, ...,
          -4.62423287e-02, -1.71163858e-02,  1.44455960e+00],
         [ 1.25058115e+00, -3.19879368e-03,  2.87119787e-03, ...,
          -6.06687417e-02, -2.07607846e-02,  2.88133999e+00],
         ...,
         [ 1.57104038e+00, -2.70470611e-02, -7.64099305e-02, ...,
          -1.02577234e+00,  3.00935329e+00,  6.62987310e+00],
         [ 1.57979881e+00, -2.36314303e-02, -8.25748254e-02, ...,
          -5.16503466e-01,  2.37480571e+00,  5.97890744e+00],
         [ 1.58769349e+00, -1.95297167e-02, -8.46352196e-02, ...,
           4.27895406e-04,  1.69780628e+00,  5.52297073e+00]]),
  'actions': array([[[ 0.02608132,  2.138234  ,  1.8916897 ]],
  
         [[ 0.06066349,  1.9349298 ,  1.7981125 ]],
  
         [[ 0.08049232,  1.6863072 ,  1.7177788 ]],
  
         ...,
  
       

In [16]:
dataset = objects[0]
oShape = list( dataset['observations'].shape )
oShape[0] = 0
oShape = tuple(oShape)
aShape = list( dataset['actions'].shape )
aShape[0] = 0
aShape = tuple(aShape)

print(oShape)
print(aShape)


(0, 11)
(0, 1, 3)


In [17]:
observations = np.empty(oShape)
actions = np.empty(aShape)
for dataset in objects:
    observations = np.vstack( ( observations, dataset['observations'] ) )
    actions = np.vstack( ( actions, dataset['actions'] ) )
#flatten


In [18]:

type(observations)


numpy.ndarray

In [19]:
observations.shape

(20000, 11)

In [22]:
actions.shape

(20000, 1, 3)

In [23]:
type( dataset['observations'].shape )

tuple

In [24]:
observations[2]

array([ 1.25058115e+00, -3.19879368e-03,  2.87119787e-03,  4.11372714e-03,
        1.91710943e-02,  5.24538455e-02, -2.15776297e-01,  2.16130659e-02,
       -6.06687417e-02, -2.07607846e-02,  2.88133999e+00])

In [26]:
keras.utils.normalize( observations[2])

array([[ 3.97052590e-01, -1.01559928e-03,  9.11589422e-04,
         1.30608558e-03,  6.08671626e-03,  1.66538054e-02,
        -6.85077791e-02,  6.86202871e-03, -1.92619895e-02,
        -6.59143413e-03,  9.14809489e-01]])

In [27]:
norOb = keras.utils.normalize( observations, axis=1 )

In [28]:
norOb[1]

array([ 0.65359665, -0.00169781,  0.00172936,  0.00222894,  0.00097102,
        0.0132227 , -0.05603891, -0.00293085, -0.02414288, -0.00893638,
        0.754197  ])

In [34]:
stats.mean( norOb[:,1])

-0.001290744519199369

In [35]:
stats.mean( norOb[1])

0.12110898577036541

In [36]:
norOb[:,1].shape

(20000,)

In [38]:
observations.ndim

2

In [39]:
actions.ndim

3

In [42]:
actions2 = keras.utils.normalize( actions, axis = actions.ndim - 1 )